apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dcp2-339.workshop.findingaids.lib.umich.edu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port: 
                  number: 80
  tls:
    - hosts:
        - dcp2-339.workshop.findingaids.lib.umich.edu
      secretName: search-tls
