apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ead-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
status: {}
