apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.dev.yml convert --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.dev.yml convert --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:arclight@db/arclight
            - name: FINDING_AID_DATA
              value: ./sample-ead
            - name: GOOGLE_ANALYTICS_DEBUG
              value: "true"
            - name: GOOGLE_ANALYTICS_TRACKING_ID
              value: UA-167959564-4
            - name: RAILS_ENV
              value: development
            - name: REDIS_URL
              value: redis://redis:6379
            - name: SOLR_URL
              value: http://solr:8983/solr/arclight
          image: dul-arclight
          imagePullPolicy: Never
          name: app
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /opt/app-root
              name: app-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/esty/github/mlibrary/dul-arclight
          name: app-hostpath0
status: {}
