include:
  template: Dependency-Scanning.gitlab-ci.yml

stages:
  - build
  - test
  - release
  - deploy

variables:
  APP_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DEPLOY_IMAGE: $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:latest

build_job:
  stage: build
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - .docker/build.sh -p always -e RAILS_ENV=production
    - docker push $APP_IMAGE
  tags:
    - docker
    - build

test_job:
  stage: test
  before_script:
    - docker info
    - docker-compose version
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $APP_IMAGE
    - .docker/build.sh --incremental -e RAILS_ENV=test
    - .docker/run_test_suite.sh
  tags:
    - docker
    - test

release_job:
  stage: release
  only:
    - master
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $APP_IMAGE
    - docker tag $APP_IMAGE $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

.deploy:
  stage: deploy
  before_script:
    - docker info
    - docker-compose version
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $APP_IMAGE
    - docker tag $APP_IMAGE $DEPLOY_IMAGE
    - docker push $DEPLOY_IMAGE
  after_script:
    - sudo systemctl restart docker-compose@dul-arclight

deploy_development:
  extends: .deploy
  environment:
    name: development
    url: https://arclight-dev.lib.duke.edu
  tags:
    - development
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/

deploy_staging:
  extends: .deploy
  environment:
    name: staging
    url: https://arclight-test.lib.duke.edu
  tags:
    - staging
  only:
    - develop
    - tags
    - /^release-.*$/
    - /^hotfix-.*$/

deploy_production:
  extends: .deploy
  environment:
    name: production
    url: https://arclight.lib.duke.edu
  tags:
    - production
  only:
    - master
  when: manual
