include:
  - project: devops/ci-config
    file: /templates/container-flexible.gitlab-ci.yml
  - project: devops/ci-config
    file: /templates/bundler-audit.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

variables:
  build_tag: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  deploy_tag: $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:latest

build:
  extends: .build

test:
  extends: .test

rubocop:
  extends: .test
  script:
    - make rubocop
  allow_failure: true

bundler-audit:
  tags:
    - test

.deploy:
  stage: deploy
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $build_tag
  script:
    - docker tag $build_tag $deploy_tag
    - docker push $deploy_tag
  after_script:
    - sudo systemctl reload-or-restart docker-stack@dul-arclight

deploy_development:
  extends: .deploy
  environment:
    name: development
    url: https://archives-dev.lib.duke.edu
  tags:
    - development
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - /^aery-.*$/

deploy_staging:
  extends: .deploy
  environment:
    name: staging
    url: https://archives-test.lib.duke.edu
  tags:
    - staging
  only:
    - develop
    - tags
    - /^release-.*$/
    - /^hotfix-.*$/

deploy_production:
  extends: .deploy
  environment:
    name: production
    url: https://archives.lib.duke.edu
  tags:
    - production
  only:
    - master
  when: manual
