---
inherit_from: .rubocop_todo.yml

require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'sample-ead/**/*'
    - 'tmp/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true # enable rubocop-rails cops

RSpec:
  Enabled: true # enable rubocop-rspec cops
