require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'sample-ead/**/*'
  TargetRubyVersion: 2.6
  DisplayCopNames: true

Layout/LineLength:
  Max: 160
  Exclude:
    - 'lib/dul_arclight/traject/ead2_config.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'lib/dul-arclight/traject/ead2_config.rb'
    - 'lib/tasks/**/*'
    - 'spec/**/*'
    - 'tasks/**/*'

Rails:
  Enabled: true
