version: '3.7'

volumes:
  pg_data:

services:
  solr:
    image: solr:8-slim
    ports:
      - "8983:8983"
    environment:
      - SOLR_JAVA_MEM=-Xms1024m -Xmx1024m
      - SOLR_HEAP=1024m
    volumes:
#      - ./solr/arclight:/var/solr/data/arclight
      - ./solr/arclight/conf:/solr_config:ro
    command:
      - solr-precreate
      - arclight
      - /solr_config

  db:
#    ports:
#      - "5432:5432"
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=arclight
      - POSTGRES_PASSWORD=arclight
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    image: dul-arclight
    build:
      dockerfile: .docker/Dockerfile.staging
      context: .
    depends_on:
      - db
      - solr
    volumes:
      - .:/opt/app-root
    ports:
      - "3000:3000"
# Uncomment for Docker Compose RubyMine Development
#      - "1234:1234"
#      - "26162:26162"
    environment:
      - DATABASE_URL=postgresql://postgres:arclight@db/arclight
      - GOOGLE_ANALYTICS_DEBUG=${GOOGLE_ANALYTICS_DEBUG:-false}
      - GOOGLE_ANALYTICS_TRACKING_ID=${GOOGLE_ANALYTICS_TRACKING_ID}
      - REDIS_URL=redis://redis:6379
      - SOLR_URL=http://solr:8983/solr/arclight
      - RAILS_ENV=development
      - FINDING_AID_DATA=./sample-ead
# Uncomment for Docker Compose RubyMine Development
#    command:
#      - tail
#      - -f
#      - /dev/null

  redis:
    image: redis:6-buster
#    ports:
#      - "6379:6379"

  resque:
    image: dul-arclight
#    ports:
#      - "8282:8282"
    depends_on:
      - db
      - redis
      - solr
    volumes:
      - .:/opt/app-root
    environment:
      - DATABASE_URL=postgresql://postgres:arclight@db/arclight
      - FINDING_AID_DATA=./sample-ead
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - SOLR_URL=http://solr:8983/solr/arclight
    healthcheck:
      disable: true
    stop_signal: SIGQUIT
    command:
      - bundle
      - exec
      - rake
      - resque:pool

  resque-web:
    image: dul-arclight
    ports:
     - "8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/opt/app-root
    environment:
      - DATABASE_URL=postgresql://postgres:arclight@db/arclight
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - SOLR_URL=http://solr:8983/solr/arclight
    healthcheck:
      disable: true
    command:
      - bundle
      - exec
      - resque-web
      - '-p'
      - '8080'
      - '-r'
      - redis:6379
      - '-F'
