apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.dev.yml convert --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: resque
  name: resque
spec:
  ports:
    - name: "8282"
      port: 8282
      targetPort: 8282
  selector:
    io.kompose.service: resque
status:
  loadBalancer: {}
