development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solr:8983/solr/umich-arclight-development" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solr:8983/solr/umich-arclight-test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solr:8983/solr/umich-arclight" %>
