---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: umich-arclight-development

test:
  <<: *default
  database: umich-arclight-test

production:
  <<: *default
  database: umich-arclight
