image_list:
  1:
    caption_html: |
      "It's so simple" Jell-O, America's most famous dessert from <a href="/catalog/umich-scl-ams0084">
      Culinary Ephemera: Gelatin and Tapioca</a>
    image: sclib_24627_0028_full_872_624__0_native.jpg
  2:
    caption_html: |
      1997 University of Michigan Football Team from <a href="/catalog/umich-bhl-943">
      Athletic Department (University of Michigan) records</a>
    image: bhl_bl001282_full_897_492__0_native.jpg
  3:
    caption_html: |
      African American family, 1889? from <a href="/catalog/umich-wcl-F-830tin">
      David V. Tinder Collection of Michigan Photography</a>
    image: wcl1ic_wcl004061_full_775_501__0_native.jpg
