image_list:
  1:
    caption_html: Image of an owl from John James Audubon's Birds of America
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-1.jpg
  2:
    caption_html: A manuscript from somewhere
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-2.jpg
  3:
    caption_html: A woodcut
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-3.jpg
  4:
    caption_html: Example caption <a href="#">with a link to somewhere</a>
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-4.jpg
  5:
    caption_html: Image from the <a href="/catalog/uaallenbldg">Allen building takeover collection</a>
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-5.jpg
  6:
    caption_html: Example caption
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-6.jpg
  7:
    caption_html: |
      Prosthetic glass eyeballs from <a href="/catalog/homartifacts_aspace_ref1241_u4n">History of Medicine
      artifacts collection</a>
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-7.jpg
  8:
    caption_html: TV0597 from Ad*Access
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-8.jpg
  9:
    caption_html: I'm Batman
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-9.jpg
  10:
    caption_html:  Example caption
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-10.jpg
  11:
    caption_html:  Example caption
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-11.jpg
  12:
    caption_html:  Example caption
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-12.jpg
  13:
    caption_html: "Ignatius Sancho: an African man of letters"
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-13.jpg
  14:
    caption_html:  Example caption
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-14.jpg
  15:
    caption_html:  Example caption
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-15.jpg
  16:
    caption_html: Viriginia Woolf's writing desk
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-16.jpg
  17:
    caption_html:  Example caption
    image_url: https://library.duke.edu/sites/default/files/rubenstein/panels/banner-17.jpg
