image_list:
  1:
    caption_html: |
      "It's so simple" Jell-O, America's most famous dessert from <a href="/catalog/umich-scl-ams0084">
      Culinary Ephemera: Gelatin and Tapioca</a>
    image: sclib_24627_0028_full_872_624__0_native.jpg
  2:
    caption_html: |
      1997 University of Michigan Football Team from <a href="/catalog/umich-bhl-943">
      Athletic Department (University of Michigan) records</a>
    image: bhl_bl001282_full_897_492__0_native.jpg
  3:
    caption_html: |
      African American family, 1889? from <a href="/catalog/umich-wcl-F-830tin">
      David V. Tinder Collection of Michigan Photography</a>
    image: wcl1ic_wcl004061_full_775_501__0_native.jpg
  4:
    caption_html: |
      Sara Purmet, from <a href="/catalog/ehll--bingham">
      Abel Bingham Family Papers, 1765-1964</a>
    image: SaraPurmet1024_1.jpg
  5:
    caption_html: |
      Excerpts of Michigan Senator Robert P. Griffin’s speech at the Dedication of the Phil Hart Sand Dunes Visitor Center from <a href="/catalog/ehll--griffin">
      Senator Robert P. Griffin Papers Collection</a>
    image: GriffinCassettePHartCenterDedicationSpeech1024_1.jpg
  6:
    caption_html: |
      "AEF in France" photographic album cover from <a href="/catalog/ehll--bourgeois">
      Mary M. Bourgeois Family Papers</a>
    image: BourgeoiseATFscrapbookcovercloseup1024_1.jpg
  7:
    caption_html: |
      City of Green Bay ferry postcard from <a href="/catalog/ehll--bacon">
      Capt. William C. Bacon, Michigan Car Ferries Collection</a>
    image: CityofGreenBayPostcardCaptBacon1024_1.jpg
  8:
    caption_html: |
      1923 Aladdin Homes Catalog from <a href="/catalog/ehll--aladdin">
      Aladdin Company Collection</a>
    image: Aladdin19231024_1.jpg
  9:
    caption_html: |
      "The Killers" one-sheet movie poster (circa 1964) from <a href="/catalog/ehll--HemingwayErnest">
      Ernest Hemingway Collection</a>
    image: EHTheKillers1.jpg
  10:
    caption_html: |
      Selection of nineteenth-century receipts from <a href="/catalog/umich-wcl-M-401bri">
      George Brinley papers</a>
    image: Brinleyreceipts_2.jpg
  11:
    caption_html: |
      Selection of childhood letters and cyanotype of Grace Abbot from <a href="/catalog/umich-wcl-M-4180-3abb">
      Abbot family papers</a>
    image: Abbotfamily4.jpg
  12:
    caption_html: |
      Pressed flowers from <a href="/catalog/umich-wcl-P-2493fre">
      Lily Frémont flower album, 1859</a>
    image: Fremont_Pressed_flowers.jpg
  13:
    caption_html: |
      Pages from  <a href="/catalog/umich-wcl-M-7252por">
      Portland & White Mountains Stage Coach records</a>
    image: PortlandWhiteMountainsStage.jpg
  14:
    caption_html: |
      Textile weaving pattern from <a href="/catalog/umich-wcl-M-3444roh">
      Jacob Rohland pattern book, 1815</a>
    image: Rohland.2.jpg
  15:
    caption_html: |
      A spectacular watercolor scene from Michigan's Upper Peninsula from<a href="/catalog/umich-wcl-P-2881lak">
      Lake Superior Scenery</a>
    image: LakeSuperiorScenery.jpg
  16:
    caption_html: |
      Studio portrait of Spanish-American and Philippine-American War veteran Lt. Grosvenor L. Townsend <a href="/catalog/umich-wcl-F-696tow">
      Grosvenor L. Townsend scrapbooks</a>
    image: Portrait-Grosvenor-Townsend.jpg
  17:
    caption_html: |
      Photograph showing Lakota chief Young Man Afraid of His Horses (Thasunke Khokiphapi) from <a href="/catalog/umich-wcl-F-1156poh">
      Richard Pohrt, Jr. Collection of Native American Photography</a>
    image: YoungManAfraidofHisHorses.jpg
  18:
    caption_html: |
      Watercolor poking fun at the 1825 fashions of Philadelphia from <a href="/catalog/umich-wcl-P-2510cla">
      Edward Williams Clay watercolors, scrapbook fragments, and silhouettes</a>
    image: Tea-fight_EdwardWilliamsClay.jpg

