rubenstein:
  name: 'David M. Rubenstein Rare Book & Manuscript Library'
  visit_note: "Register online to request material for use in our reading room and track the status of your requests. Requests for material must be made 2 full business days in advance of your visit. Most of our collections are stored at the Library Service Center, our off-site repository."
  description: "The holdings of the Rubenstein Rare Book & Manuscript Library range from ancient papyri to records of modern advertising. There are over 10,000 manuscript collections containing more than 20 million individual manuscript items. Only a portion of these collections and items are discoverable on this site. Others may be found in the library catalog."
  building: 'Rubenstein Library'
  address1: '411 Chapel Drive'
  address2: ''
  city: 'Durham'
  state: 'NC'
  zip: '27708'
  country: 'USA'
  phone: '919-660-5822'
  contact_info: 'special-collections@duke.edu'
  thumbnail_url: 'https://library.duke.edu/sites/default/files/rubenstein/arclight/duke-rubenstein.jpg'
  #request_types:
  #  google_form:
  #    request_url: 'https://docs.google.com/a/stanford.edu/forms/d/e/1FAIpQLSeOamhY_IcFw4sPnz0ddwWWkrPaHbM5wp7JVbOLOL_mIusEyw/viewform'
  #    request_mappings: "document_url=entry.1980510262&collection_name=entry.619150170&collection_creator=entry.14428541&eadid=entry.996397105&containers=entry.1125277048&title=entry.862815208"
ua:
  name: 'Duke University Archives'
  visit_note: "Register online to request material for use in our reading room and track the status of your requests. Requests for material must be made 2 full business days in advance of your visit. Most of our collections are stored at the Library Service Center, our off-site repository."
  description: "The Duke University Archives is the official repository for records of Duke University and has a charge to make them available for use in accordance with policies approved by Duke University's Board of Trustees, administration and faculty. In addition to the official records of the university, the Duke University Archives holds campus publications; audiovisual materials by and about Duke University; papers and selected publications of Duke University faculty members; records of Duke University student and employee organizations and dissertations, theses, final projects and senior honors papers produced by Duke University students."
  building: 'Rubenstein Library'
  address1: '411 Chapel Drive'
  address2: ''
  city: 'Durham'
  state: 'NC'
  zip: '27708'
  country: 'USA'
  phone: '919-660-5822'
  contact_info: 'special-collections@duke.edu'
  thumbnail_url: 'https://library.duke.edu/sites/default/files/rubenstein/arclight/duke-ua.jpg'
  #request_types:
  #  aeon_web_ead:
  #    request_url: 'https://sample.request.com'
  #    request_mappings: 'Action=10&Form=31&Value=ead_url'
adf:
  name: 'American Dance Festival Archives'
  visit_note: "Materials from the ADF Archives may be viewed by appointment in the David M. Rubenstein Rare Book & Manuscript Library at Duke University. Visits may be arranged in advance by contacting the ADF archivist at adfarchives@americandancefestival.org. Visitors will need to comply with Duke's registration and security policies."
  description: "The American Dance Festival Archives serves as the repository for records of enduring historical value created and collected by ADF. The Archives preserves its collections for use by the dance community, including students, scholars, and the general public."
  building: 'Rubenstein Library'
  address1: '411 Chapel Drive'
  address2: ''
  city: 'Durham'
  state: 'NC'
  zip: '27708'
  country: 'USA'
  phone: '919-684-6402'
  contact_info: 'adfarchives@americandancefestival.org'
  thumbnail_url: 'https://library.duke.edu/sites/default/files/rubenstein/arclight/duke-adf.jpg'
  #request_types:
  #  aeon_external_request_endpoint:
  #    request_url: https://example.com/aeon/aeon.dll
  #    request_mappings:
  #      url_params:
  #        Action: 11
  #        Type: 200
  #      static:
  #        SystemId: ArcLight
  #        ItemInfo1: manuscript
  #      accessor:
  #        ItemTitle: collection_name
