bhl:
  name: 'University of Michigan. Bentley Historical Library'
  description: 'The Bentley Historical Library collects the materials for and promotes the study of the histories of two great, intertwined institutions, the State of Michigan and the University of Michigan. The Library is open without fee to the public, and we welcome researchers regardless of academic or professional affiliation.'
  visit_note: ''
  building: ''
  address1: '1150 Beal Avenue'
  address2: ''
  city: 'Ann Arbor'
  state: 'MI'
  zip: '48109-2113'
  country: 'USA'
  phone: ''
  contact_info: 'bentley.ref@umich.edu'
  thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Bhlexterior.jpg/150px-Bhlexterior.jpg'
scrc:
  name: 'University of Michigan. Special Collections Research Center'
  description: 'In keeping with the University Library’s mission to collect, describe, preserve, and make available the record of human knowledge, the Special Collections Research Center acquires, cares for, interprets, and promotes the use of important collections of unique, rare, primary source, and other material in all formats and in a variety of subject areas.'
  visit_note: ''
  building: 'Harlan Hatcher Graduate Library (South)'
  address1: '913 S. University Avenue'
  address2: ''
  city: 'Ann Arbor'
  state: 'MI'
  zip: '48109-1190'
  country: 'USA'
  phone: ''
  contact_info: 'special.collections@umich.edu'
  thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/9/96/University_of_Michigan_library_stacks.JPG'
clements:
  name: 'University of Michigan. William L. Clements Library'
  description: 'The William L. Clements Library is a rare book and manuscript repository located on the University of Michigan’s central campus in Ann Arbor, Michigan.'
  visit_note: ''
  building: ''
  address1: '909 South University Avenue'
  address2: ''
  city: 'Ann Arbor'
  state: 'MI'
  zip: '48109'
  country: 'USA'
  phone: ''
  contact_info: 'clements-reference@umich.edu'
  thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/University_of_Michigan_August_2013_179_%28William_L._Clements_Library%29.jpg'
clarke:
  name: 'Central Michigan University. Clarke Historical Library'
  description: 'The Clarke Historical Library collects, preserves, and promotes collections including the history of Michigan and the Old Northwest Territory, the history of Central Michigan University, as well as other topics.'
  visit_note: ''
  building: ''
  address1: '250 East Preston Street'
  address2: ''
  city: 'Mount Pleasant'
  state: 'MI'
  zip: '48859'
  country: 'USA'
  phone: ''
  contact_info: 'clarke@cmich.edu'
  thumbnail_url: 'https://www.cmich.edu/images/default-source/academic-affairs-division/cmu-libraries/about/support-the-libraries/20210723_support_universityseal_0086fdf1a7f-50e7-4d64-a7ca-f7979508b7a2.jpg'
vrc:
  name: 'University of Michigan. History of Art. Visual Resources Collection'
  description: "The VRC maintains nearly two million images of art. The collection's roots are more than 90 years old and developed as a teaching collection to support University of Michigan faculty and students. Through these online finding aids, we hope to help you connect with our vast resources of images of art, architecture, and artifacts."
  visit_note: ''
  building: '45 Tappan Hall'
  address1: '2855 South University Avenue'
  address2: ''
  city: 'Ann Arbor'
  state: 'MI'
  zip: '48109'
  country: 'USA'
  phone: ''
  contact_info: 'vrum@umich.edu'
  thumbnail_url: 'https://mapproxy.studentlife.umich.edu/images/tappan-hall/AXP2S1698.jpg'
archivemi:
  name: 'The Archives of Michigan is responsible for preserving the records of Michigan government and other public institutions. The collections also include documents, maps, photographs and film from private individuals and organizations.'
  visit_note: ''
  building: ''
  address1: '702 West Kalamazoo Street'
  address2: ''
  city: 'Lansing'
  state: 'MI'
  zip: '48915'
  country: 'USA'
  phone: ''
  contact_info: 'Archives@Michigan.gov'
  thumbnail_url: 'https://www.michigan.gov/mhc/-/media/Project/Websites/mhc/images/archives/archives_womanresearcher.jpg'
mlibraryead:
  name: "MLibrary's Finding Aids site provides access to finding aids or descriptive inventories for archival records and manuscript collections not held in the Special Collections Research Center."
  visit_note: ''
  building: ''
  address1: '913 South University Avenue'
  address2: ''
  city: 'Ann Arbor'
  state: 'MI'
  zip: '48109'
  country: 'USA'
  phone: ''
  contact_info: 'dlps-help@umich.edu'
  thumbnail_url: 'https://www.lib.umich.edu/static/f7ffa2d7bc8b7d2c2e56eaf08f237c8b/53249/AerialsNov08(186)Stock-a.webp'
