apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pg-data
  name: pg-data
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 100Mi
status: {}
