apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-data
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 50Gi
status: {}
