version: '3.7'

networks:
  default:
    name: "arclight-${RAILS_ENV}"

services:
  db:
    image: "${POSTGRES_IMAGE}"
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD

  solr:
    image: "${SOLR_IMAGE}"

  app:
    image: "${APP_IMAGE}"
    depends_on:
      - db
      - solr
    environment:
      - RAILS_ENV
      - DATABASE_URL
      - FINDING_AID_DATA
      - REDIS_URL
      - SOLR_URL
    entrypoint:
      - wait-for-it
      - db:5432
      - '--'
    command:
      - /usr/libexec/s2i/run
