version: '3.7'

volumes:
  pg_data:
  solr_data:

services:
  solr:
    ports:
      - "${SOLR_PORT}:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores

  db:
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    volumes:
      - ..:/opt/app-root
    ports:
      - "${RAILS_PORT}:3000"
