version: '3.7'

services:
  app:
    volumes:
      - ../spec/fixtures:/data:ro
  solr:
    volumes:
      - ../solr/arclight/conf:/solr_config:ro
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - "${SOLR_CORE}"
      - /solr_config
