version: '3.7'

services:
  app:
    volumes:
      - ../spec/fixtures:/data:ro
    environment:
      - RAILS_ENV=test
      - FINDING_AID_DATA=spec/fixtures
    command:
      - bundle
      - exec
      - rake
      - seed:fixtures
      - db:reset
      - spec

  solr:
    logging:
      driver: none
