version: '3.7'

volumes:
  pg_data:

services:
  solr:
    ports:
      - "${SOLR_PORT}:8983"
    volumes:
      - ../solr/arclight:/var/solr/data/arclight

  db:
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    volumes:
      - ..:/opt/app-root
    ports:
      - "${RAILS_PORT}:3000"

  redis:
    image: "${REDIS_IMAGE}"

  resque:
    image: "${APP_IMAGE}"
    depends_on:
      - db
      - redis
      - solr
    volumes:
      - ..:/opt/app-root
    environment:
      - RAILS_ENV
      - DATABASE_URL
      - FINDING_AID_DATA
      - REDIS_URL
      - SOLR_URL
    healthcheck:
      disable: true
    stop_signal: SIGQUIT
    entrypoint:
      - wait-for-it
      - db:5432
      - '--'
    command:
      - bundle
      - exec
      - rake
      - resque:pool

  resque-web:
    image: "${APP_IMAGE}"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ..:/opt/app-root
    environment:
      - RAILS_ENV
      - DATABASE_URL
      - REDIS_URL
      - SOLR_URL
    healthcheck:
      disable: true
    entrypoint:
      - wait-for-it
      - redis:6379
      - '--'
    command:
      - bundle
      - exec
      - resque-web
      - '-p'
      - '8080'
      - '-r'
      - redis:6379
      - '-F'
