apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.dev.yml convert --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.dev.yml convert --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:arclight@db/arclight
            - name: FINDING_AID_DATA
              value: /opt/app-data
            - name: GOOGLE_ANALYTICS_DEBUG
              value: "true"
            - name: GOOGLE_ANALYTICS_TRACKING_ID
              value: "G-D0JL9WVR0D"
            - name: RAILS_ENV
              value: production
            - name: RAILS_SERVE_STATIC_FILES
              value: "true"
            - name: REDIS_URL
              value: redis://redis:6379
            - name: SOLR_URL
              value: "http://$(SOLR_SERVICE_HOST):$(SOLR_SERVICE_PORT)/solr/arclight"
          image: ghcr.io/mlibrary/arclight/umich-arclight-unstable:latest
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
