apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.dev.yml convert --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: resque
  name: resque
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: resque
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.dev.yml convert --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: resque
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - command:
            - bundle
            - exec
            - rake
            - resque:pool
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:arclight@db/arclight
            - name: FINDING_AID_DATA
              value: /opt/app-data/
            - name: RAILS_ENV
              value: development
            - name: REDIS_URL
              value: redis://redis:6379
            - name: SOLR_URL
              value: http://solr:8983/solr/arclight
          image: estythomas/umich-arclight-staging:20220217.4
          imagePullPolicy: Always
          name: resque
          ports:
            - containerPort: 8282
          resources: {}
          volumeMounts:
            - mountPath: /opt/app-data
              name: ead-data
      restartPolicy: Always
      volumes:
        - name: ead-data
          persistentVolumeClaim:
            claimName: ead-data
status: {}
