---
name: Continuous Integration

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions
  push:
  pull_request:

#env:
#  LAUTH_API_DB_HOST: 127.0.0.1
#  LAUTH_API_DB_DATABASE: test
#  LAUTH_API_DB_USER: user
#  LAUTH_API_DB_PASSWORD: password

jobs:

  ci:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.6.3'

#    services:
#      mariadb:
#        image: mariadb:latest
#        ports:
#          - 3306:3306
#        env:
#          MYSQL_USER: user
#          MYSQL_PASSWORD: password
#          MYSQL_DATABASE: test
#          MYSQL_ROOT_PASSWORD: password
#        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Bundle Install
        run: bundle install
      - name: Rubocop
        run: bundle exec rubocop
#      - name: RSpec
#        run: bundle exec rspec
