---
name: Continuous Integration

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions
  push:
  pull_request:

env:
  RAILS_ENV: test
  SOLR_URL: "http://127.0.0.1:8983/solr/test"

jobs:

  ci:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.6.3'

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Start Solr
        run: docker run -d -p 8983:8983 -v $(pwd)/solr/arclight/conf:/test/conf solr:8 solr-precreate test /test
      - name: Bundle Install
        run: bundle install
      - name: DB Migration
        run: bundle exec rake db:migrate
      - name: Rubocop
        run: bundle exec rubocop
      - name: RSpec
        run: bundle exec rspec
